---

# [kibana-7.x]
# name=Elastic repository for 7.x packages
# baseurl=https://artifacts.elastic.co/packages/7.x/yum
# gpgcheck=1
# gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
# enabled=1
# autorefresh=1
# type=rpm-md

- hosts: elk
  become: true
  vars_files:
  - vars.yml

  tasks:
  - name: Get Kibana
    yum:
      name: "kibana-{{ elastic_version }}"
      state: present

  - name: Make sure Kibana autostarts, but is stopped until it is properly configured
    systemd:
      name: kibana
      enabled: yes
      state: stopped

  - name: Make Kibana available on all network interfaces
    lineinfile: >
      dest=/etc/kibana/kibana.yml
      regexp='^server.host'
      line='server.host: "0.0.0.0"'

  - name: Create the Kibana logging directory
    file:
      path: /var/log/kibana/
      state: directory
      owner: kibana
      group: kibana

  - name: Enable persistent Kibana logs
    lineinfile: >
      dest=/etc/kibana/kibana.yml
      regexp='^logging.dest'
      line='logging.dest: /var/log/kibana/kibana.log'

  - name: Start Kibana
    systemd:
      name: kibana
      enabled: yes
      state: restarted

  - name: Wait for Kibana to become available
    wait_for:
      port: 5601
      delay: 5
