#==========================  Modules configuration ============================
filebeat.config.modules:
  path: /etc/filebeat/modules.d/*.yml
  enabled: true

filebeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  syslog:
    enabled: true
  auth:
    enabled: true
#------------------------------- Auditd Module -------------------------------
- module: auditd
  log:
    enabled: true
#------------------------------ Logstash Module ------------------------------
- module: logstash
  log:
    enabled: true
#----------------------------- PostgreSQL Module ------------------------------
- module: postgresql
  log:
    enabled: true
    var.paths: ["/var/lib/pgsql/10/data/log/*.log*"]
    
#=========================== Filebeat inputs =============================

# List of inputs to fetch data.
# filebeat.inputs:
# - type: log
#   enabled: true
#   paths:
#     - /var/log/kibana/kibana.log
#   json.message_key: log
#  fields:
#    type: kibana

filebeat.autodiscover:
  # List of enabled autodiscover providers
  providers:
    - type: docker
#       templates:
#         - condition:
#             equals.docker.container.image: busybox
#           config:
#             - type: log
#               paths:
#                 - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
- add_docker_metadata: ~
- add_host_metadata: ~

logging.level: info
logging.to_files: true
# logging.to_syslog: false
logging.files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  enabled: false
  hosts: ["localhost:9200"]

#----------------------------- Logstash output ---------------------------------
output.logstash:
  enabled: true
  hosts: ["localhost:5044"]

#============================== Kibana =====================================

setup.kibana:
  host: "localhost:5601"

setup.dashboards.enabled: true
setup.ilm.enabled: false

#============================== Xpack Monitoring =====================================

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
  hosts: ["localhost:9200"]
